# Generated by Django 3.1.7 on 2021-05-30 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organs', '0001_initial'),
        ('organic_units', '0001_initial'),
        ('work_types', '0001_initial'),
        ('partners', '0002_auto_20210526_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorganicunit',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalorganicunit',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='historicalworktype',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalworktype',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='organ',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='organicunit',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='worktype',
            name='owner',
        ),
        migrations.AlterField(
            model_name='historicalpartner',
            name='organ',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organs.organ'),
        ),
        migrations.AlterField(
            model_name='historicalpartner',
            name='organic_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organic_units.organicunit'),
        ),
        migrations.AlterField(
            model_name='historicalpartner',
            name='work_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='work_types.worktype'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='organ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='organs.organ'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='organic_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='organic_units.organicunit'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='work_types.worktype'),
        ),
        migrations.DeleteModel(
            name='HistoricalOrgan',
        ),
        migrations.DeleteModel(
            name='HistoricalOrganicUnit',
        ),
        migrations.DeleteModel(
            name='HistoricalWorkType',
        ),
        migrations.DeleteModel(
            name='Organ',
        ),
        migrations.DeleteModel(
            name='OrganicUnit',
        ),
        migrations.DeleteModel(
            name='WorkType',
        ),
    ]
