# Generated by Django 3.1.7 on 2021-05-16 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partner_healths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='healths',
        ),
    ]
