# Generated by Django 3.2 on 2021-05-10 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=True)),
                ('folded', models.BooleanField(default=True)),
                ('position', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('below', 'Below'), ('top', 'Top')], default='left', max_length=10)),
                ('style', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Configs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scroll', models.CharField(default='content', max_length=10)),
                ('mode', models.CharField(default='fullwidth', max_length=20)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_footer', to='profiles.bars')),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_navbar', to='profiles.bars')),
                ('toolbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_toolbar', to='profiles.bars')),
            ],
        ),
        migrations.CreateModel(
            name='Layouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(default='style1', max_length=10)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.configs')),
            ],
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(default='default', max_length=15)),
                ('navbar', models.CharField(default='defaultDark', max_length=15)),
                ('toolbar', models.CharField(default='default', max_length=15)),
                ('footer', models.CharField(default='default', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_scrollbars', models.BooleanField(default=True)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.layouts')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.themes')),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.settings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
