# Generated by Django 3.2 on 2021-05-11 18:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bars',
            new_name='Bar',
        ),
        migrations.RenameModel(
            old_name='Configs',
            new_name='Config',
        ),
        migrations.RenameModel(
            old_name='Layouts',
            new_name='Layout',
        ),
        migrations.RenameModel(
            old_name='Profiles',
            new_name='Profile',
        ),
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
        migrations.RenameModel(
            old_name='Themes',
            new_name='Theme',
        ),
    ]
