version: "3"

services:
    djangorest:
        build: .
        container_name: djangorest
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - .env
        volumes:
            - .:/app
        ports:
            - "8000:8000"
