# Generated by Django 3.1.7 on 2021-05-14 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2)),
                ('q2', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2)),
                ('q3', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2)),
                ('q4', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2)),
                ('q5', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2)),
                ('q5_detail', models.CharField(blank=True, max_length=200, null=True)),
                ('fit', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
