# Generated by Django 3.1.7 on 2021-05-27 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20210526_0019'),
        ('symptoms', '0002_auto_20210526_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='partners.partner'),
        ),
    ]
