# Generated by Django 3.2 on 2021-04-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='q10',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='health',
            name='q11',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='health',
            name='q12',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='health',
            name='q2',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='health',
            name='q3',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='health',
            name='q4',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='health',
            name='q5',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='health',
            name='q6',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='health',
            name='q7',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='health',
            name='q8',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='health',
            name='q9',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=2),
        ),
    ]
