# Generated by Django 3.1.7 on 2021-05-15 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='image',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='photo',
        ),
    ]
