# Generated by Django 3.1.7 on 2021-05-16 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partner_healths'),
        ('users', '0003_auto_20210515_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='partner_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='user',
            name='partner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.partner'),
        ),
    ]
