# Generated by Django 3.1.7 on 2021-05-29 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20210526_0132'),
        ('users', '0003_auto_20210528_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.setting'),
        ),
    ]
