# Generated by Django 3.1.7 on 2021-05-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210516_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido Materno'),
        ),
    ]
