# Generated by Django 3.1.7 on 2021-06-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210529_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='username',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nombre usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre usuario'),
        ),
    ]
