# Generated by Django 3.1.7 on 2021-05-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healths', '0002_auto_20210514_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='fit',
            field=models.BooleanField(default=True),
        ),
    ]
