# Generated by Django 3.1.7 on 2021-05-26 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_style', models.CharField(default='layout1', max_length=255)),
                ('layout_config_scroll', models.CharField(default='content', max_length=255)),
                ('layout_config_navbar_position', models.CharField(default='left', max_length=255)),
                ('layout_config_navbar_display', models.BooleanField(default=True)),
                ('layout_config_navbar_folded', models.BooleanField(default=False)),
                ('layout_config_toolbar_position', models.CharField(default='below', max_length=255)),
                ('layout_config_toolbar_style', models.CharField(default='fixed', max_length=255)),
                ('layout_config_toolbar_display', models.BooleanField(default=True)),
                ('layout_config_footer_position', models.CharField(default='below', max_length=255)),
                ('layout_config_footer_display', models.BooleanField(default=True)),
                ('layout_config_footer_style', models.CharField(default='fixed', max_length=255)),
                ('layout_config_mode', models.CharField(default='fullwidth', max_length=255)),
                ('custom_scrollbars', models.BooleanField(default=True)),
                ('theme_main', models.CharField(default='default', max_length=255)),
                ('theme_navbar', models.CharField(default='defaultDark', max_length=255)),
                ('theme_toolbar', models.CharField(default='default', max_length=255)),
                ('theme_footer', models.CharField(default='default', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
