# Generated by Django 3.1.7 on 2021-05-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='theme',
            new_name='theme_footer',
        ),
        migrations.AddField(
            model_name='setting',
            name='custom_scrollbars',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='layout_config_footer_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='layout_config_footer_position',
            field=models.CharField(default='below', max_length=255),
        ),
        migrations.AddField(
            model_name='setting',
            name='layout_config_footer_style',
            field=models.CharField(default='fixed', max_length=255),
        ),
        migrations.AddField(
            model_name='setting',
            name='layout_config_mode',
            field=models.CharField(default='fullwidth', max_length=255),
        ),
        migrations.AddField(
            model_name='setting',
            name='layout_config_navbar_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='layout_config_navbar_folded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setting',
            name='layout_config_navbar_position',
            field=models.CharField(default='left', max_length=255),
        ),
        migrations.AddField(
            model_name='setting',
            name='layout_config_scroll',
            field=models.CharField(default='content', max_length=255),
        ),
        migrations.AddField(
            model_name='setting',
            name='layout_config_toolbar_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='layout_config_toolbar_position',
            field=models.CharField(default='below', max_length=255),
        ),
        migrations.AddField(
            model_name='setting',
            name='layout_config_toolbar_style',
            field=models.CharField(default='fixed', max_length=255),
        ),
        migrations.AddField(
            model_name='setting',
            name='layout_style',
            field=models.CharField(default='layout1', max_length=255),
        ),
        migrations.AddField(
            model_name='setting',
            name='theme_main',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='setting',
            name='theme_navbar',
            field=models.CharField(default='defaultDark', max_length=255),
        ),
        migrations.AddField(
            model_name='setting',
            name='theme_toolbar',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
