# Generated by Django 3.1.7 on 2021-05-26 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_setting_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='setting',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='setting',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
